@php $editing = $achievement->exists; @endphp
<x-layouts.admin :title="($editing ? 'Edit' : 'Tambah').' Prestasi'">
    <form method="POST" action="{{ $editing ? route('admin.achievements.update', $achievement) : route('admin.achievements.store') }}" enctype="multipart/form-data" x-data="{ saving: false }" @submit="saving = true">@csrf @if($editing)@method('PUT')@endif
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><a href="{{ route('admin.achievements.index') }}" class="text-sm font-medium text-primary-700">← Kembali ke prestasi</a><h2 class="mt-3 text-2xl font-semibold tracking-tight text-slate-950">{{ $editing ? 'Edit prestasi' : 'Tambah prestasi' }}</h2></div><button type="submit" class="btn-primary shrink-0 !py-2" :disabled="saving" x-text="saving ? 'Menyimpan…' : 'Simpan prestasi'">Simpan prestasi</button></div>
        @if($errors->any())<div class="mt-6 rounded-xl bg-rose-50 p-4 text-sm text-rose-800">Prestasi belum dapat disimpan. Periksa field yang ditandai.</div>@endif
        <div class="mt-7 grid gap-7 xl:grid-cols-[2fr_1fr]"><section class="rounded-2xl bg-white p-6 ring-1 ring-slate-900/10"><div class="grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label for="title" class="label">Judul prestasi</label><input id="title" name="title" type="text" value="{{ old('title', $achievement->title) }}" class="input" required>@error('title')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div><div><label for="participant" class="label">Nama peserta atau tim</label><input id="participant" name="participant" type="text" value="{{ old('participant', $achievement->participant) }}" class="input"></div><div><label for="rank" class="label">Peringkat</label><input id="rank" name="rank" type="text" value="{{ old('rank', $achievement->rank) }}" class="input" placeholder="Contoh: Juara 1"></div><div><label for="category" class="label">Kategori</label><input id="category" name="category" type="text" value="{{ old('category', $achievement->category) }}" class="input" placeholder="Akademik / Nonakademik" required></div><div><label for="level" class="label">Tingkat</label><select id="level" name="level" class="input" required>@foreach(\App\Models\Achievement::LEVELS as $level)<option value="{{ $level }}" @selected(old('level', $achievement->level) === $level)>{{ ucfirst($level) }}</option>@endforeach</select></div><div><label for="organizer" class="label">Penyelenggara</label><input id="organizer" name="organizer" type="text" value="{{ old('organizer', $achievement->organizer) }}" class="input"></div><div><label for="achieved_date" class="label">Tanggal prestasi</label><input id="achieved_date" name="achieved_date" type="date" value="{{ old('achieved_date', $achievement->achieved_date?->format('Y-m-d')) }}" class="input" required>@error('achieved_date')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div><div class="sm:col-span-2"><label for="description" class="label">Deskripsi</label><textarea id="description" name="description" rows="6" class="input">{{ old('description', $achievement->description) }}</textarea></div></div></section>
            <aside class="flex flex-col gap-6"><section class="rounded-2xl bg-white p-6 ring-1 ring-slate-900/10"><fieldset><legend class="font-semibold text-slate-950">Status publikasi</legend><div class="mt-4 flex flex-col gap-3">@foreach(['draft' => 'Draft — belum tampil', 'published' => 'Published — tampil di website'] as $value => $label)<label class="flex items-center gap-3 text-base text-slate-700 sm:text-sm"><input type="radio" name="status" value="{{ $value }}" class="size-5 border-slate-300 text-primary-600 sm:size-4" @checked(old('status', $achievement->status) === $value)>{{ $label }}</label>@endforeach</div></fieldset></section><section class="rounded-2xl bg-white p-6 ring-1 ring-slate-900/10"><label for="cover" class="label">Foto prestasi</label><input id="cover" name="cover" type="file" accept="image/jpeg,image/png,image/webp" class="input"><p class="mt-1 text-sm text-slate-500">JPG, PNG, atau WebP. Maksimal 3 MB.</p>@error('cover')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror @if($achievement->cover)<img src="{{ asset('storage/'.$achievement->cover) }}" alt="Foto saat ini" class="mt-4 aspect-video w-full rounded-xl object-cover outline outline-1 -outline-offset-1 outline-black/5">@endif</section></aside></div>
    </form>
</x-layouts.admin>
