@php $section = request('section', 'profiles'); @endphp
<x-layouts.admin title="Alumni">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 class="text-2xl font-semibold tracking-tight text-slate-950">Kelola alumni</h2><p class="mt-2 text-base text-slate-600">Kelola profil publik dan verifikasi registrasi alumni.</p></div>@if($section === 'profiles')@can('alumni.create')<a href="{{ route('admin.alumni.create') }}" class="btn-primary shrink-0 !py-2 !pr-3 !pl-2"><x-icon name="plus" class="size-4" />Tambah alumni</a>@endcan @endif</div>
    <nav class="mt-7 flex gap-1 overflow-x-auto border-b border-slate-900/10" aria-label="Bagian alumni"><a href="{{ route('admin.alumni.index', ['section' => 'profiles']) }}" class="whitespace-nowrap border-b-2 px-3 py-3 text-sm font-medium {{ $section === 'profiles' ? 'border-primary-600 text-primary-700' : 'border-transparent text-slate-600 hover:text-slate-950' }}">Profil alumni</a><a href="{{ route('admin.alumni.index', ['section' => 'submissions']) }}" class="whitespace-nowrap border-b-2 px-3 py-3 text-sm font-medium {{ $section === 'submissions' ? 'border-primary-600 text-primary-700' : 'border-transparent text-slate-600 hover:text-slate-950' }}">Registrasi masuk @if($pendingCount)<span class="ml-1 rounded-full bg-gold-100 px-2 py-0.5 text-xs text-gold-900">{{ $pendingCount }}</span>@endif</a></nav>

    @if($section === 'profiles')
        <form method="GET" class="mt-6 grid gap-3 sm:grid-cols-[minmax(0,1fr)_12rem_auto]"><input type="hidden" name="section" value="profiles"><div><label for="q" class="sr-only">Cari alumni</label><input id="q" name="q" type="search" value="{{ request('q') }}" class="input !py-2" placeholder="Cari nama alumni"></div><div><label for="status" class="sr-only">Status</label><select id="status" name="status" class="input !py-2"><option value="">Semua status</option>@foreach(\App\Models\Alumni::STATUSES as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div><button type="submit" class="btn-outline !py-2">Terapkan</button></form>
        <div class="mt-7 divide-y divide-slate-900/10 border-y border-slate-900/10">@forelse($alumni as $person)<article class="flex flex-col justify-between gap-4 py-5 sm:flex-row sm:items-center"><div class="flex min-w-0 items-center gap-4">@if($person->photo)<img src="{{ asset('storage/'.$person->photo) }}" alt="" class="size-14 shrink-0 rounded-full object-cover outline outline-1 -outline-offset-1 outline-black/5">@else<div class="flex size-14 shrink-0 items-center justify-center rounded-full bg-primary-50"><x-icon name="graduation-cap" class="size-6 text-primary-400" /></div>@endif<div class="min-w-0"><h3 class="truncate font-semibold text-slate-950">{{ $person->name }}</h3><p class="mt-1 text-base text-slate-600 sm:text-sm">Lulusan {{ $person->graduation_year ?: '—' }} · {{ $person->occupation ?: $person->university ?: 'Aktivitas belum diisi' }}</p><p class="mt-1 text-sm text-slate-500">{{ ucfirst($person->status) }} · {{ $person->is_public ? 'Diizinkan publik' : 'Privat' }}</p></div></div><div class="flex shrink-0 gap-2">@can('alumni.update')<a href="{{ route('admin.alumni.edit', $person) }}" class="rounded-lg px-2.5 py-1.5 text-sm font-medium text-primary-700 hover:bg-primary-50">Edit</a>@endcan @can('alumni.delete')<form method="POST" action="{{ route('admin.alumni.destroy', $person) }}" onsubmit="return confirm(@js('Pindahkan profil '.$person->name.' ke sampah?'))">@csrf @method('DELETE')<button type="submit" class="rounded-lg px-2.5 py-1.5 text-sm font-medium text-rose-700 hover:bg-rose-50">Hapus</button></form>@endcan</div></article>@empty<p class="py-12 text-center text-base text-slate-500">Belum ada profil alumni. Tambahkan profil pertama.</p>@endforelse</div><div class="mt-7">{{ $alumni->links() }}</div>
    @else
        <form method="GET" class="mt-6 flex max-w-sm gap-3"><input type="hidden" name="section" value="submissions"><div class="min-w-0 flex-1"><label for="submission_status" class="sr-only">Status registrasi</label><select id="submission_status" name="submission_status" class="input !py-2"><option value="">Semua status</option>@foreach(\App\Models\AlumniSubmission::STATUSES as $status)<option value="{{ $status }}" @selected(request('submission_status', 'pending') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></div><button type="submit" class="btn-outline !py-2">Terapkan</button></form>
        <div class="mt-7 divide-y divide-slate-900/10 border-y border-slate-900/10">@forelse($submissions as $submission)<article class="py-5"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div class="min-w-0"><h3 class="font-semibold text-slate-950">{{ $submission->name }}</h3><p class="mt-1 text-base text-slate-600 sm:text-sm">Lulusan {{ $submission->graduation_year ?: '—' }} · {{ $submission->occupation ?: $submission->university ?: 'Aktivitas belum diisi' }}</p><p class="mt-2 text-sm text-slate-500">{{ $submission->email }}{{ $submission->phone ? ' · '.$submission->phone : '' }} · Dikirim {{ $submission->created_at->diffForHumans() }}</p>@if($submission->testimonial)<blockquote class="mt-3 max-w-3xl border-l-2 border-primary-200 pl-4 text-base text-slate-600 sm:text-sm">{{ $submission->testimonial }}</blockquote>@endif</div>@if($submission->status === 'pending')@can('alumni.verify')<div class="flex shrink-0 flex-wrap gap-2"><form method="POST" action="{{ route('admin.alumni.submissions.approve', $submission) }}" onsubmit="return confirm(@js('Setujui registrasi '.$submission->name.' dan publikasikan profilnya?'))">@csrf<button type="submit" class="rounded-lg bg-primary-50 px-2.5 py-1.5 text-sm font-medium text-primary-800 hover:bg-primary-100">Setujui dan publikasikan</button></form><form method="POST" action="{{ route('admin.alumni.submissions.reject', $submission) }}" onsubmit="return confirm(@js('Tolak registrasi alumni '.$submission->name.'?'))">@csrf<button type="submit" class="rounded-lg px-2.5 py-1.5 text-sm font-medium text-rose-700 hover:bg-rose-50">Tolak</button></form></div>@endcan @else<span class="shrink-0 text-sm font-medium text-slate-500">{{ ucfirst($submission->status) }}</span>@endif</div></article>@empty<p class="py-12 text-center text-base text-slate-500">Tidak ada registrasi alumni pada status ini.</p>@endforelse</div><div class="mt-7">{{ $submissions->links() }}</div>
    @endif
</x-layouts.admin>
