@php $editing = $teacher->exists; @endphp
<x-layouts.admin :title="($editing ? 'Edit' : 'Tambah').' Guru & Tendik'">
    <form method="POST" action="{{ $editing ? route('admin.teachers.update', $teacher) : route('admin.teachers.store') }}" enctype="multipart/form-data" x-data="{ saving: false }" @submit="saving = true" class="max-w-5xl">
        @csrf @if($editing)@method('PUT')@endif
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><a href="{{ route('admin.teachers.index') }}" class="text-sm font-medium text-primary-700">← Kembali ke guru dan tendik</a><h2 class="mt-3 text-2xl font-semibold tracking-tight text-slate-950">{{ $editing ? 'Edit data' : 'Tambah guru atau tendik' }}</h2><p class="mt-2 text-base text-slate-600">Masukkan informasi profesional yang aman untuk ditampilkan kepada publik.</p></div><button type="submit" class="btn-primary shrink-0 !py-2" :disabled="saving" x-text="saving ? 'Menyimpan…' : 'Simpan data'">Simpan data</button></div>
        @if($errors->any())<div class="mt-6 rounded-xl bg-rose-50 p-4 text-base text-rose-800 sm:text-sm">Data belum dapat disimpan. Periksa field yang ditandai.</div>@endif

        <div class="mt-7 grid items-start gap-8 lg:grid-cols-[13rem_1fr]">
            <aside class="rounded-2xl bg-white p-5 ring-1 ring-slate-900/10">
                @if($teacher->photo)<img src="{{ asset('storage/'.$teacher->photo) }}" alt="Foto {{ $teacher->name }}" class="aspect-[4/5] w-full rounded-xl object-cover outline outline-1 -outline-offset-1 outline-black/5">@else<div class="flex aspect-[4/5] items-center justify-center rounded-xl bg-primary-50"><x-icon name="user-round" class="size-12 text-primary-300" /></div>@endif
                <label for="photo" class="label mt-4">{{ $editing && $teacher->photo ? 'Ganti foto' : 'Foto' }}</label><input id="photo" name="photo" type="file" accept="image/jpeg,image/png,image/webp" class="input"><p class="mt-1 text-sm text-slate-500">JPG, PNG, atau WebP. Maksimal 3 MB.</p>@error('photo')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror
            </aside>

            <div class="flex flex-col gap-7">
                <section class="rounded-2xl bg-white p-6 ring-1 ring-slate-900/10">
                    <fieldset><legend class="font-semibold text-slate-950">Jenis tenaga</legend><div class="mt-4 grid gap-3 sm:grid-cols-2">@foreach(['guru' => ['Guru','Pendidik atau pengajar mata pelajaran'], 'tendik' => ['Tenaga kependidikan','Staf administrasi dan tenaga pendukung']] as $value => [$label, $description])<label class="flex cursor-pointer gap-3 rounded-xl p-4 ring-1 ring-slate-900/10 has-[:checked]:bg-primary-50 has-[:checked]:ring-primary-600"><input type="radio" name="type" value="{{ $value }}" class="mt-0.5 size-5 shrink-0 border-slate-300 text-primary-600 focus:ring-primary-600 sm:size-4" @checked(old('type', $teacher->type) === $value) required><span><span class="block font-medium text-slate-950">{{ $label }}</span><span class="mt-1 block text-base text-slate-600 sm:text-sm">{{ $description }}</span></span></label>@endforeach</div>@error('type')<p class="mt-2 text-sm text-rose-700">{{ $message }}</p>@enderror</fieldset>
                    <div class="mt-6 grid gap-5 sm:grid-cols-2">
                        <div class="sm:col-span-2"><label for="name" class="label">Nama lengkap dan gelar</label><input id="name" name="name" type="text" value="{{ old('name', $teacher->name) }}" class="input" required>@error('name')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
                        <div><label for="position" class="label">Jabatan</label><input id="position" name="position" type="text" value="{{ old('position', $teacher->position) }}" class="input" placeholder="Contoh: Waka Kurikulum">@error('position')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
                        <div><label for="subject" class="label">Mata pelajaran</label><input id="subject" name="subject" type="text" value="{{ old('subject', $teacher->subject) }}" class="input" placeholder="Kosongkan untuk tenaga kependidikan">@error('subject')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
                        <div class="sm:col-span-2"><label for="education" class="label">Pendidikan terakhir</label><input id="education" name="education" type="text" value="{{ old('education', $teacher->education) }}" class="input" placeholder="Contoh: S1 Pendidikan Matematika">@error('education')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div>
                    </div>
                </section>

                <section class="rounded-2xl bg-white p-6 ring-1 ring-slate-900/10"><h3 class="font-semibold text-slate-950">Tampilan website</h3><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label for="order" class="label">Urutan tampil</label><input id="order" name="order" type="number" min="0" max="9999" value="{{ old('order', $teacher->order ?? 0) }}" class="input" required>@error('order')<p class="mt-1 text-sm text-rose-700">{{ $message }}</p>@enderror</div><div class="flex flex-col gap-4 sm:pt-7"><label class="flex items-start gap-3 text-base text-slate-700 sm:text-sm"><input id="is_active" name="is_active" type="checkbox" value="1" class="mt-0.5 size-5 rounded border-slate-300 text-primary-600 sm:size-4" @checked(old('is_active', $teacher->is_active))><span><span class="block font-medium text-slate-950">Status aktif</span><span class="block text-slate-500">Nonaktifkan saat sudah tidak bertugas.</span></span></label><label class="flex items-start gap-3 text-base text-slate-700 sm:text-sm"><input id="is_public" name="is_public" type="checkbox" value="1" class="mt-0.5 size-5 rounded border-slate-300 text-primary-600 sm:size-4" @checked(old('is_public', $teacher->is_public))><span><span class="block font-medium text-slate-950">Tampilkan di direktori publik</span><span class="block text-slate-500">Matikan jika datanya belum siap dipublikasikan.</span></span></label></div></div></section>
            </div>
        </div>
    </form>
</x-layouts.admin>
